version: '3.9'


services:
  nginx:
    container_name: web_nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./public_html:/public_html
      - ./conf.d:/etc/nginx/conf.d
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt

    ports:
      - "80:80"
      - "443:443"


  certbot:
    container_name: certbot
    image: certbot/certbot
    env_file:
      - .env
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email admin@admin.com --agree-tos --no-eff-email -d $DOMAIN_NAME -d www.$DOMAIN_NAME
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data/:/usr/share/nginx/html/letsencrypt
    depends_on:
      - web-nginx
