version: '3'

services:
  nginx:
    container_name: web_nginx
    image: nginx:alpine
    restart: always
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./data/public_html:/public_html
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/nginx/ssl
      - ./data/certbot/www:/var/www/certbot

    ports:
      - "80:80"
      - "443:443"


  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/logs:/var/log/letsencrypt
      - ./data/certbot/www/:/var/www/certbot

