version: '3.9'


services:
  nginx:
    container_name: web_nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./data/public_html:/public_html
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/dhparam:/etc/nginx/dhparam
      - ./data/certbot/conf:/etc/nginx/ssl
      - ./data/certbot/www:/var/www/certbot

    ports:
      - "80:80"
      - "443:443"


  certbot:
    container_name: certbot
    image: certbot/certbot
    env_file:
      - .env
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email $EMAIL_NAME --agree-tos --no-eff-email -d $DOMAIN_NAME -d www.$DOMAIN_NAME
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/logs:/var/log/letsencrypt
      - ./data/certbot/www/:/var/www/certbot
    depends_on:
      - web-nginx
